/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Italk2learn */

#ifndef _Included_iT2L
#define _Included_iT2L
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Italk2learn
 * Method:    speechrecognition
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_Italk2learn_sendNewAudioChunk
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     Italk2learn
 * Method:    openASRListener
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Italk2learn_initSpeechRecognitionEngine
  (JNIEnv *, jobject);

/*
 * Class:     Italk2learn
 * Method:    closeASRListener
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Italk2learn_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
